import fs from 'fs';
import path from 'path';

const CONTRACT_BASE_DIR = path.resolve('contracts/packages/efp-model/3.0.0');
const OUTPUT_FILE = path.resolve('packages/efp-model/src/generated/types.ts');

function ensureDirectoryExistence(filePath) {
  const dirname = path.dirname(filePath);
  if (fs.existsSync(dirname)) {
    return true;
  }
  ensureDirectoryExistence(dirname);
  fs.mkdirSync(dirname);
}

function camelToPascal(str) {
  return str.replace(/(^\w|-\w)/g, (g) => g.replace(/-/, '').toUpperCase());
}

function resolveRefName(ref) {
  const basename = path.basename(ref, '.schema.json');
  return camelToPascal(basename);
}

function generateTypes() {
  console.log('Generating TypeScript types from EFP JSON Schemas (v3.0.0)...');
  
  const files = {
    common: [
      'entity-reference.schema.json',
      'participant.schema.json',
      'provenance.schema.json',
      'record-metadata.schema.json',
    ],
    entities: [
      'object.schema.json',
      'marker.schema.json',
      'place.schema.json',
    ],
    facts: [
      'association.schema.json',
      'observation.schema.json',
      'measurement.schema.json',
      'event.schema.json',
    ],
    projections: [
      'object-summary.schema.json',
      'marker-summary.schema.json',
      'place-summary.schema.json',
    ]
  };

  let tsContent = `/**
 * This file is AUTOMATICALLY GENERATED.
 * DO NOT EDIT THIS FILE MANUALLY.
 * Instead, modify the canonical JSON Schemas in /contracts/packages/efp-model/3.0.0/
 * and run 'npm run contracts:generate' to regenerate this file.
 */

`;

  const allSchemas = {};

  // Read all schemas
  for (const [group, filenames] of Object.entries(files)) {
    for (const filename of filenames) {
      const fullPath = path.join(CONTRACT_BASE_DIR, group, filename);
      const schema = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
      allSchemas[filename] = schema;
    }
  }

  // Generate type helpers
  tsContent += `export type JsonValue =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonValue }
  | JsonValue[];

`;

  // Process schemas
  const processedTypes = new Set();

  function processSchema(schema, schemaName) {
    if (processedTypes.has(schemaName)) return '';
    processedTypes.add(schemaName);

    let output = '';
    const title = schema.title || resolveRefName(schemaName);
    const description = schema.description || '';

    if (description) {
      output += `/**\n * ${description.split('\n').join('\n * ')}\n */\n`;
    }

    if (schema.type === 'object') {
      output += `export interface ${title} {\n`;
      const requiredFields = schema.required || [];

      for (const [propName, prop] of Object.entries(schema.properties || {})) {
        const isRequired = requiredFields.includes(propName);
        const opt = isRequired ? '' : '?';

        if (prop.description) {
          output += `  /** ${prop.description} */\n`;
        }

        let propType = 'any';
        if (prop.$ref) {
          propType = resolveRefName(prop.$ref);
        } else if (Array.isArray(prop.type)) {
          // Handle type unions (e.g. ["string", "null"])
          propType = prop.type.map(t => {
            if (t === 'integer') return 'number';
            if (t === 'null') return 'null';
            return t;
          }).join(' | ');
        } else if (prop.type === 'string') {
          if (prop.enum) {
            propType = prop.enum.map(e => `'${e}'`).join(' | ');
          } else {
            propType = 'string';
          }
        } else if (prop.type === 'number' || prop.type === 'integer') {
          propType = 'number';
        } else if (prop.type === 'boolean') {
          propType = 'boolean';
        } else if (prop.type === 'array') {
          if (prop.items && prop.items.$ref) {
            propType = `${resolveRefName(prop.items.$ref)}[]`;
          } else if (prop.items && prop.items.type === 'string') {
            propType = 'string[]';
          } else {
            propType = 'any[]';
          }
        } else if (prop.type === 'object') {
          if (prop.properties) {
            // Inline nested object
            let nestedType = '{\n';
            const subRequired = prop.required || [];
            for (const [subName, subProp] of Object.entries(prop.properties)) {
              const subOpt = subRequired.includes(subName) ? '' : '?';
              if (subProp.description) {
                nestedType += `    /** ${subProp.description} */\n`;
              }
              let subType = 'any';
              if (Array.isArray(subProp.type)) {
                subType = subProp.type.map(t => {
                  if (t === 'integer') return 'number';
                  if (t === 'null') return 'null';
                  return t;
                }).join(' | ');
              } else if (subProp.type === 'string') {
                if (subProp.enum) {
                  subType = subProp.enum.map(e => `'${e}'`).join(' | ');
                } else {
                  subType = 'string';
                }
              } else if (subProp.type === 'number' || subProp.type === 'integer') {
                subType = 'number';
              } else if (subProp.type === 'boolean') {
                subType = 'boolean';
              } else if (subProp.type === 'array') {
                subType = 'any[]';
              }
              nestedType += `    ${subName}${subOpt}: ${subType};\n`;
            }
            nestedType += '  }';
            propType = nestedType;
          } else {
            propType = 'Record<string, any>';
          }
        }

        output += `  ${propName}${opt}: ${propType};\n`;
      }
      output += `}\n\n`;
    }

    return output;
  }

  // Common schemas first
  for (const filename of files.common) {
    tsContent += processSchema(allSchemas[filename], filename);
  }

  // Entities
  for (const filename of files.entities) {
    tsContent += processSchema(allSchemas[filename], filename);
  }

  // Facts
  for (const filename of files.facts) {
    tsContent += processSchema(allSchemas[filename], filename);
  }

  // Projections
  for (const filename of files.projections) {
    tsContent += processSchema(allSchemas[filename], filename);
  }

  ensureDirectoryExistence(OUTPUT_FILE);
  fs.writeFileSync(OUTPUT_FILE, tsContent, 'utf8');
  console.log(`TypeScript types successfully generated to: ${OUTPUT_FILE}`);
}

generateTypes();
